baseURL: "https://about.wingleung.me/"
title: About Tony
pagination:
  pagerSize: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

ignoreLogs: ['warning-goldmark-raw-html']

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Tony - Digital Marketing Professional in Hong Kong
  description: "I am a digital marketing professional based in Hong Kong with 13 years of experience in website marketing, SEO, SEM, and social media strategy for the Southeast Asia market."
  keywords: [Digital Marketing, Social Media Marketing, Website Marketing, SEO, SEM, Content Strategy, Hong Kong]
  author: Tony 
  # author: ["Me", "You"] # multiple authors
  images: ["images/wl-icon.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: true
  
  # Add social parameters for new Hugo version
  social:
    twitter: chtwlaa
    facebook_admin: ""

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/wl-icon.png"
    favicon16x16: "images/wl-icon.png"
    favicon32x32: "images/wl-icon.png"
    apple_touch_icon: ""
    safari_pinned_tab: ""
    
  customCSS:
    - css/custom.css

  label:
    text: "About Tony"
    icon: ""
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Greetings, this is Tony \U0001F44B"
    subtitle: "A digital marketer with 13 years in the Southeast Asia market, focusing on website marketing and content marketing strategies."
    imageUrl: "images/me.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: About Tony
    buttons:
      - name: "Portfolios"
        url: "https://www.wdigitalagency.com/portfolios/"
      - name: "Contact"
        url: "/contact/"

  # home-info mode
  homeInfoParams:
    Title: "Hello world! \U0001F44B"
    Content: Welcome to my first github page in 2024.

  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/chtwlaa/"
    - name: threads
      url: "https://www.threads.net/@chtwlaa"
    - name: linkedin
      url: "https://www.linkedin.com/in/twlaa/"
    - name: github
      url: "https://github.com/twl-dev"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
      # Add actual Google Analytics ID when available
      googleAnalytics: "" # Add your GA ID here
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: About
      name: about
      url: /about/
      weight: 10
    - identifier: Portfolios
      name: portfolios
      url: https://www.wdigitalagency.com/portfolios/
      weight: 20
    - identifier: blog
      name: blog
      url: https://www.wingleung.me/
      weight: 30
    - identifier: contact
      name: contact
      url: /contact/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

permalinks:
  posts: /:year/:month/:title/ 